using MOVIE_DATABASE;
using System;


List<Move> moveTitles = new List<Move>()
{
    { new Move("Star Wars","Science fiction"  ) },
    { new Move("Dune","Science fiction"  ) },
    { new Move("Once upon a time in the West","Western"  ) },
    { new Move("Serenity","Science fiction") },
    { new Move("50 First Dates","Romantic comedy") },
    { new Move("Down with love","Romantic comedy") },
    { new Move("The good the bad and the ugly","Western"  ) },
    { new Move("Blade Runner","Science fiction"  ) },
    { new Move("Ender's game","Science fiction"  ) },
    { new Move("No country for old men","Thriller"  ) },
    { new Move("The 6th sense","Thriller"  ) },
    { new Move("The matrix","Science fiction"  ) },
};


bool run = true;
while (run)
{
    List<Move> foundMoves = new List<Move>();

    //this string array provides the names for the menu which is generated by menu by number
    //and menu select method 
    string[] menu =
    {
            "Thriller","Science Fiction","Western","Romantic Comedy"
    };
    string slectedCategory = MenuBuyNumber.MenuSelect(menu).ToLower();
    Console.WriteLine();

    //Filters through all the movies selects only the movies in chosen category 
    foundMoves = moveTitles.Where(c => c.Category.ToLower() == slectedCategory).ToList();

    //lists the movies in the chosen category 
    foreach (Move move in foundMoves)
    {
        Console.WriteLine(move.GetDetails());
    }

    //Gatekeeper 
    while (true)
    {
        Console.WriteLine("would like to contiu y/n");
        string anser = Console.ReadLine().ToLower().Trim();
        if (anser == "y" || anser == "n")
        {
            if (anser == "y")
            {
                break;
            }
            else
            {
                run = false;
                break;
            }
        }
        else
        {
            Console.WriteLine("Invalid response");
        }
    }

}





